---
name: mysql

releases:
- name: cf-mysql
  version: latest

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest
- alias: ubuntu-trusty
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-300000
  max_in_flight: 1
  serial: true
  update_watch_time: 10000-300000

instance_groups:
- name: db
  azs: ((azs))
  networks:
  - name: default
  stemcell: xenial
  vm_type: default
  persistent_disk: 10240
  instances: 3
  jobs:
  - name: mysql
    release: cf-mysql
    properties:
      cf_mysql:
        port: 3306
        mysql:
          admin_username: admin
          admin_password: ((db_admin_password))
          tls:
            ca_certificate: ((/certs/wildcard.ca))
            server_certificate: ((/certs/wildcard.certificate))
            server_key: ((/certs/wildcard.private_key))
          seeded_databases:
            - name: credhub
              username: credhub
              password: ((/database/credhub_db_password))
            - name: uaa
              username: uaa
              password: ((/database/credhub_uaa_db_password))
            - name: gogs
              username: gogs
              password: ((/database/gogs_db_password))
            - name: grafana
              username: grafana
              password: ((/database/grafana_db_password))
          galera_healthcheck:
            endpoint_password: ((galera_healthcheck_endpoint_password))
            db_password: ((galera_healthcheck_db_password))
          cluster_health:
            password: ((cluster_health_password))
  - name: smoke-tests-user
    release: cf-mysql
    properties:
      cf_mysql:
        smoke_tests:
          db_password: ((mysql_smoke_tests_db_password))

- name: arbitrator
  instances: 1
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: xenial
  jobs:
  - release: cf-mysql
    name: arbitrator
    properties:
      cf_mysql:
        mysql:
          admin_password: ((db_admin_password))
          galera_healthcheck:
            endpoint_password: ((galera_healthcheck_endpoint_password))

- name: proxy
  instances: 1 #this needs to be 1 due to proxy limitations.  TODO: Implement bosh dns
  azs: [z1]
  networks:
  - name: default
    static_ips: ((mySQL_proxy_ip))
  vm_type: default
  stemcell: xenial
  jobs:
  - name: proxy
    release: cf-mysql
    properties:
      cf_mysql:
        mysql:
          port: 3306
        proxy:
          api_aggregator_port: 8082
          api_port: 8080
          #api_uri: ((mysql_proxy_url))
          api_username: proxy
          api_password: ((mysql_proxy_api_password))
          port: 3306
    provides:
      mysql-database:
        as: mysql-database
        shared: true

- name: bootstrap-vm
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: xenial
  jobs:
  - {release: cf-mysql, name: bootstrap}

- name: rejoin-unsafe-vm
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: xenial
  jobs:
  - {release: cf-mysql, name: rejoin-unsafe}

- name: verify-cluster-schemas-vm
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: xenial
  jobs:
  - name: verify-cluster-schemas
    release: cf-mysql
    properties:
      cf_mysql:
        mysql:
          admin_password: ((db_admin_password))
          galera_healthcheck:
            endpoint_password: ((galera_healthcheck_endpoint_password))

- name: smoke-tests-vm
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: xenial
  jobs:
  - name: smoke-tests
    release: cf-mysql
    properties:
      cf_mysql:
        mysql:
          admin_password: ((db_admin_password))
        proxy:
          api_password: ((mysql_proxy_api_password))
        smoke_tests:
          db_password: ((mysql_smoke_tests_db_password))
          standalone_tests_only: true

variables:
#MySQL Vars
- name: mysql_smoke_tests_db_password
  type: password
- name: mysql_proxy_api_password
  type: password
- name: galera_healthcheck_endpoint_password
  type: password
- name: galera_healthcheck_db_password
  type: password
- name: cluster_health_password
  type: password
- name: db_admin_password
  type: password

#DB Passwords
- name: /database/credhub_db_password
  type: password
- name: /database/credhub_uaa_db_password
  type: password
- name: /database/grafana_db_password
  type: password
- name: /database/gogs_db_password
  type: password