platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
  - name: pcf-env-report
outputs:
  - name: email
params:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  ENV:
  CF_API:

run:
  path: pcf-env-report/tasks/deployed-products/task.sh
