platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
    tag: final

inputs:
  - name: pcf-apply-pipeline
outputs:
  - name: email
params:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  ENV:

run:
  path: pcf-apply-pipeline/tasks/apply-changes/task.sh
