resources:
- name: pcf-run-report
  type: git
  source:
    uri: "https://github.com/mylucidreality/standalone-bosh.git"
    private_key: ((git_key.private_key))

- name: schedule
  type: time
  source:
   start: ((env_report_schedule_start))
   stop: ((env_report_schedule_stop))
   location: America/New_York
   interval: ((env_report_interval))

- name: pipeline_image
  type: docker-image
  source:
    repository: ((docker-registry))/clitools
    insecure_registries: [ ((docker-registry)) ]

jobs:
- name: gather-data
  plan:
  - get: schedule
    trigger: true
  - get: pcf-run-report
  - get: pipeline_image
  - task: generate-files
    file: pcf-run-report/tasks/env-report/task.yml
    image: pipeline_image
    params:
      BOSH_ADMIN_CLIENT: ((BOSH_ADMIN_CLIENT))
      PCF_SCRT: ((PCF_SCRT))
      PCF_URL: ((PCF_URL))
      PCF_CERT: ((PCF_CERT))
      PCF_ENV: ((PCF_ENV))
      RPT_GIT: ((RPT-GIT))
      GIT_CERT: ((git_key.private_key))
      PCF_DIRECTOR: ((PCF_DIRECTOR))
      CF_API: ((CF_API))
      OPSMAN_DOMAIN_OR_IP_ADDRESS: ((opsman_url))
      OPSMAN_USERNAME: ((opsman_admin.username))
      OPSMAN_PASSWORD: ((opsman_admin.password))
