#Delete
- type: remove
  path: /instance_groups/name=database

- type: remove
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=PostgreSQL

- type: remove
  path: /variables/name=postgres_grafana_password

- type: remove
  path: /releases/name=postgres

#add
- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/database?
  value:
    type: mysql
    port: 3306
    password: ((/database/grafana_db_password))
    name: grafana
    user: grafana

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/session?
  value:
    provider: mysql
    provider_port: 3306
    provider_password: ((/database/grafana_db_password))
    provider_name: grafana
    provider_user: grafana