- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/auth/ldap?
  value:
    config: |
      verbose_logging = true
      [[servers]]

      host = "((ldap_host))"
      port = 389
      use_ssl = false
      start_tls = false
      ssl_skip_verify = true
      bind_dn = "((ldap_bind_dn))"
      bind_password = """((/ldap_user.password))"""
      search_filter = "(|(sAMAccountName=%s)(userPrincipalName=%s))"
      search_base_dns = ["((ldap_user_search_base_dns))"]
      group_search_base_dns = ["((ldap_group_search_base_dns))"]

      [servers.attributes]
      name = "givenName"
      surname = "sn"
      username = "cn"
      member_of = "memberOf"
      email =  "mail"

      [[servers.group_mappings]]
      group_dn = "((grafana_group_dn))"
      org_role = "Admin"

    enabled: true